### ISSUE TITLE
Add https://suche.dasnetzundich.de

### ISSUE THREAD

**Issue by Happyfeet01** [dalf/searx-instances#33] opened 2020-04-06 05:03 UTC
I switched the server, after that the search engine was deleted from the list. 

* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment] 2020-04-06 10:02
The instance is already registered: https://github.com/dalf/searx-instances/blob/fcde28e7d0afcddaf3821ae8abe0aa0fa31f8e1f/searxinstances/instances.yml#L384

The instance appears on "Offline / Error" tab : there is a "Connection timed out" error.

It requires some investigation.

**Comment by dalf** [comment] 2020-04-06 14:12
Are you using a firewall ? fail2ban or something similar ?

You can send me an email if you prefer : alex.andre@al-f.net

---

Whatever the HTTP headers are:

|                        | curl | httpx.Client (1) | httpx.AsyncClient (2)  |
|------------------------|------|--------------|--------------------|
| My Internet connection | OK   | OK           | OK                 |
| searx.space            | OK   | OK           | Connection Timeout |

* (1) use [urllib3](https://urllib3.readthedocs.io/en/latest/)
* (2) use asyncio, [h11](https://github.com/python-hyper/h11) and [h2](https://github.com/python-hyper/hyper-h2)

An easy way to reproduce the case ( where httpx.AsyncClient timeout ) :
```python
import asyncio
s = await asyncio.open_connection('suche.dasnetzundich.de', 443)
print(s)
```

On searx.space I get the result after 2 minutes.

searx-stats2 uses httpx.AsyncClient to send multiple requests in parallel, so there is a Connection Timeout. I can't reproduce on my computer.

**Comment by Happyfeet01** [comment] 2020-04-06 15:40
Okay,

I have a look at the server. I switched to an new server. Fail2ban was installed today. I have a look at the server logs.

**Comment by Happyfeet01** [comment] 2020-04-06 16:00
I have whitelisted the ipv4 and the ipv6 address. Now I wait

**Comment by dalf** [comment] 2020-04-07 06:59
I will end up to use tcpdump :
* curl : ok
* httpx: ko

```python 
a = time(); await asyncio.open_connection('suche.dasnetzundich.de', 443); print(time() - a)                                                                                                                                    
130.15125346183777
````

either curl and httpx shouldn't be able to connect, either they both should work.

I don't know if you have a 130 seconds delay somewhere in your configuration ?

**Comment by Happyfeet01** [comment] 2020-04-07 07:03
> I will end up to use tcpdump :
> 
> * curl : ok
> 
> * httpx: ko
> 
> 
> 
> ```python 
> 
> a = time(); await asyncio.open_connection('suche.dasnetzundich.de', 443); print(time() - a)                                                                                                                                    
> 
> 130.15125346183777
> 
> ````
> 
> 
> 
> either curl and httpx shouldn't be able to connect, either they both should work.
> 
> 
> 
> I don't know if you have a 130 seconds delay somewhere in your configuration ?
> 
> 

Not really. I have a look into to compose file and restart the container. I have no idea what the reason.

**Comment by dalf** [comment] 2020-04-07 09:44
Now it is working, so tcpdump traces are the same.
The good thing is that now suche.dasnetzundich.de is shown online.
The bad thing is that I don't know why it was not working.

Perhaps a Cloudflare bot protection.

**Comment by Happyfeet01** [comment] 2020-04-07 09:59
Maybe....

**Comment by dalf** [comment] 2020-04-07 11:38
I close the issue but I keep an eye on suche.dasnetzundich.de

**Closed by dalf** 2020-04-07 11:38 UTC
Labels: instance, instance add
