### ISSUE TITLE
No published source codes of Searx instances in https://searx.space/ (potentially breaking AGPLv3)

### ISSUE THREAD

**Issue by TheEvilSkeleton** [dalf/searx-instances#66] opened 2020-07-10 16:28 UTC
the AGPL v3 **requires** users to publish the source codes of their forks. whenever i look at an official instance (https://searx.space/), the maintainers do not provide the source code of their fork.

Suggestions:
- Provide the source code of the forks of each instance in https://searx.space
- Ask the maintainers to change the hyperlink of "Source code" ([simple/base.html#L55](https://github.com/asciimoo/searx/blob/4ca0d8cb0fd6c0e6b1301a6e8577aea6d928e9dc/searx/templates/simple/base.html#L55)) to their own Git repository

**Comment by unixfox** [comment] 2020-07-10 16:47
Duplicate of https://github.com/dalf/searx-instances/issues/23

**Comment by TheEvilSkeleton** [comment] 2020-07-10 16:50
apologies

**Closed** 2020-07-10 16:50 UTC
