### ISSUE TITLE
Python version + questions

### ISSUE THREAD

**Issue by Pofilo** [dalf/searx-instances#7] opened 2020-02-24 20:01 UTC
Hello @dalf,

To add #6, I wanted to use the python tool you made but I faced a problem with the version of python used.

```
Collecting requirements-update.txt
  Could not find a version that satisfies the requirement requirements-update.txt (from versions: )
No matching distribution found for requirements-update.txt
```

My virtualenv was in 3.7 and I saw in `setup.py` that the version used is 3.6, is there a specific reason ? Plus, the dependencies are a bit outdated (ex: https://pypi.org/project/PyYAML/5.1.2/)

Now, the questions:

- Are you okay to push directly on master for adding instances ? Do we do PR ?
- How do we make sure that the person asking to remove an instance is the owner of the instance ?

Thanks :)

**Comment by dalf** [comment] 2020-02-25 09:03
> My virtualenv was in 3.7 and I saw in setup.py that the version used is 3.6, is there a specific reason ? 

No reason. It should work with any Python version >= 3.6 (perhaps even 3.5).

> Are you okay to push directly on master for adding instances ? Do we do PR ?

I'm okay to push directly to master, that is the intent:
* PR directly from owner means the commit messages can be messy, and if we refuse the PR because of that, some owners may just give up. The searxinstances.update tool is here to solve this.
 * A PR after the issue basically means two persons review the change, I don't think it is necessary.

> How do we make sure that the person asking to remove an instance is the owner of the instance ?

In fact, there is no way to that with the current (and previous) process.
What can happen:
|                  | Remove from anonymous                     | Remove by owner                      |
|------------------|-------------------------------------------|---------------------------------------|
| **Add by anonymous** | Can be the same author  (B)               | Owner has to prove (s)he is the owner (A) |
| **Add by owner**     | Anonymous has to prove s(he) is the owner | Same author                           |

* (A) How a owner can prove (s)he is the owner ? Most probably by sending an email from the instance domain.
* (B): Some instance can appear / disappear with this list without the owner consent.

---

#### Out of topic

Something like Letsencrypt would be better:
* A settings.yml to declare the instance as public
* searx would register to searx.space (with a ACME http / dns challenge)
* note: the ACME challenge would be everyday (or at least way more often than once every 3 months).
* If the instance is stopped or the "public" is change --> the instance disappear.

But it requires a database AND a reliable backup otherwise the instance list may disappear.

To have the both world, we can keep a git repository and use a bot:
* to deal with the ACME challenges.
* create the commits.

**Comment by dalf** [comment] 2020-02-28 14:08
I can't reproduce this bug with Python 3.7 (from Ubuntu 18.04):
```
Collecting requirements-update.txt
  Could not find a version that satisfies the requirement requirements-update.txt (from versions: )
No matching distribution found for requirements-update.txt
```

What if you try to install one dependency at a time ?

**Comment by Pofilo** [comment] 2020-02-28 15:34
I don't know how I had this error:
`pip3 install -r requirements-update.txt` works fine. Maybe I forgot the `-r`.

Thanks for the answers.
For the `Out of topic` answer, I don't really know what is the best and what is worth it.

**Comment by dalf** [comment] 2020-03-01 18:10
I close the issue. Feel free to re-open.

**Closed by dalf** 2020-03-01 18:10 UTC
Labels: meta
